services:
  db:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
  web:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000/tcp"
    depends_on:
      - db
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_HOST: db
volumes:
  postgres: